services:
  postgres:
    image: postgres:latest
    container_name: postgres_proj
    volumes:
      - postgresql_data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app_network

  data:
    image: redis:latest
    container_name: redis_proj_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network


volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge