spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: saurav
    password: saurav

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true




